version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "open-sea"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nd6wmhajti22"
s3_prefix = "open-sea"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
