AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: open-sea
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 3
    Environment:
        Variables:
          ASSETS_TABLE_NAME: !Ref Assets

Resources:
  GetAssetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:      
      Handler: index.getAsset
      CodeUri: open-sea/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /asset/{tokenId}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Assets
  Assets:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: "TokenId"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "TokenId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Asset function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/asset/"
  HelloWorldFunction:
    Description: "Get Asset Lambda Function ARN"
    Value: !GetAtt GetAssetFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Get Asset function"
    Value: !GetAtt GetAssetFunctionRole.Arn
